* partial 7, rbindlist alternatives

#+begin_quote
Setup 1
# A tibble: 7 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del       1.54s    1.55s     0.643     244MB     1.65     7    18      10.9s <NULL>
2 mod_l30         513.92ms 544.45ms     1.84      255MB     1.65    19    17      10.3s <NULL>
3 mod_l30_brl     704.62ms 741.22ms     1.34      277MB     2.02    14    21      10.4s <NULL>
4 mod_l30_edfbrl… 464.36ms 502.79ms     1.98      241MB     1.69    20    17      10.1s <NULL>
5 mod_l30_vcl     710.77ms 740.73ms     1.35      277MB     2.02    14    21      10.4s <NULL>
6 mod_l30_edfvcl… 456.32ms 492.72ms     1.95      241MB     1.56    20    16      10.2s <NULL>
7 mod_l30_edfvcl…  451.9ms 478.74ms     2.09      246MB     1.49    21    15      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
  C-c C-c  C-c C-c  C-c C-c# A tibble: 7 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>           <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del          7.3s  7.62s     0.131    6.07GB    0.984     2    15      15.2s <NULL>
2 mod_l30               2.3s  2.35s     0.413    5.36GB    1.41      5    17      12.1s <NULL>
3 mod_l30_brl          2.53s  2.59s     0.384    5.38GB    1.34      4    14      10.4s <NULL>
4 mod_l30_edfbrl_asDT   2.3s  2.34s     0.426    5.35GB    1.45      5    17      11.7s <NULL>
5 mod_l30_vcl          2.41s  2.43s     0.398    5.37GB    1.10      4    11        10s <NULL>
6 mod_l30_edfvcl_setDT 2.41s  2.43s     0.398    5.35GB    0.697     4     7        10s <NULL>
7 mod_l30_edfvcl_asDT  2.41s  2.43s     0.398    5.35GB    0         4     0        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 7 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>           <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         889ms  906ms      1.09     410MB    1.09     11    11      10.1s <NULL>
2 mod_l30              436ms  466ms      2.15     478MB    0.683    22     7      10.2s <NULL>
3 mod_l30_brl          520ms  552ms      1.79     503MB    0.896    18     9        10s <NULL>
4 mod_l30_edfbrl_asDT  425ms  458ms      2.14     456MB    0.682    22     7      10.3s <NULL>
5 mod_l30_vcl          512ms  539ms      1.84     503MB    0.971    19    10      10.3s <NULL>
6 mod_l30_edfvcl_setDT 428ms  453ms      2.17     456MB    0.690    22     7      10.1s <NULL>
7 mod_l30_edfvcl_asDT  427ms  452ms      2.20     475MB    0.599    22     6        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 7 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del       1.59s    1.65s     0.609     244MB     1.48     7    17      11.5s <NULL>
2 mod_l30         549.07ms 567.65ms     1.73      255MB     1.54    18    16      10.4s <NULL>
3 mod_l30_brl     730.75ms 767.73ms     1.29      277MB     1.88    13    19      10.1s <NULL>
4 mod_l30_edfbrl… 480.14ms 514.62ms     1.94      241MB     1.55    20    16      10.3s <NULL>
5 mod_l30_vcl     735.94ms 756.63ms     1.31      277MB     1.97    14    21      10.6s <NULL>
6 mod_l30_edfvcl… 485.31ms 539.06ms     1.86      241MB     1.47    19    15      10.2s <NULL>
7 mod_l30_edfvcl…  496.3ms 536.68ms     1.78      246MB     1.38    18    14      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 7 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>           <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         7.86s  7.92s     0.126    6.07GB     1.07     2    17      15.8s <NULL>
2 mod_l30              2.31s  2.34s     0.417    5.36GB     2.42     5    29        12s <NULL>
3 mod_l30_brl          2.43s  2.45s     0.397    5.38GB     1.59     4    16      10.1s <NULL>
4 mod_l30_edfbrl_asDT  2.21s  2.22s     0.446    5.35GB     1.34     5    15      11.2s <NULL>
5 mod_l30_vcl          2.39s  2.41s     0.411    5.37GB     1.23     5    15      12.2s <NULL>
6 mod_l30_edfvcl_setDT 2.25s  2.27s     0.433    5.35GB     1.30     5    15      11.5s <NULL>
7 mod_l30_edfvcl_asDT  2.25s  2.27s     0.441    5.35GB     1.32     5    15      11.3s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 7 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>           <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         986ms  994ms      1.01     410MB    1.01     11    11      10.9s <NULL>
2 mod_l30              493ms  505ms      1.95     478MB    0.779    20     8      10.3s <NULL>
3 mod_l30_brl          555ms  570ms      1.69     503MB    0.794    17     8      10.1s <NULL>
4 mod_l30_edfbrl_asDT  471ms  474ms      2.08     456MB    0.692    21     7      10.1s <NULL>
5 mod_l30_vcl          556ms  573ms      1.72     503MB    0.766    18     8      10.4s <NULL>
6 mod_l30_edfvcl_setDT 472ms  477ms      2.06     456MB    0.588    21     6      10.2s <NULL>
7 mod_l30_edfvcl_asDT  476ms  482ms      2.03     475MB    0.581    21     6      10.3s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 6, with epiprocess updates on branch

#+begin_quote
Setup 1
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.31s    1.37s     0.712     244MB     3.20     8    36      11.2s <NULL>
 2 mod_a_re        1.99s    2.02s     0.496     663MB     2.78     5    28      10.1s <NULL>
 3 mod_c2c         1.16s    1.19s     0.837     292MB     2.98     9    32      10.8s <NULL>
 4 mod_c2c2     990.52ms    1.04s     0.966     275MB     3.09    10    32      10.3s <NULL>
 5 mod_c2c2vc      1.12s    1.24s     0.796     289MB     3.28     8    33      10.1s <NULL>
 6 mod_c2c2br      1.25s    1.29s     0.775     297MB     3.68     8    38      10.3s <NULL>
 7 mod_f           3.35s    3.38s     0.297     763MB     3.46     3    35      10.1s <NULL>
 8 mod_k        948.23ms  966.4ms     1.04      284MB     3.30    11    35      10.6s <NULL>
 9 mod_k2       506.12ms  521.5ms     1.82      185MB     2.78    19    29      10.4s <NULL>
10 mod_k3       452.26ms 466.09ms     2.13      167MB     2.90    22    30      10.3s <NULL>
11 mod_l        676.67ms 687.89ms     1.44      289MB     3.18    15    33      10.4s <NULL>
12 mod_l0       690.41ms 700.28ms     1.42      288MB     3.13    15    33      10.6s <NULL>
13 mod_l2       660.14ms 674.59ms     1.41      299MB     2.91    15    31      10.6s <NULL>
14 mod_l20      670.28ms 709.99ms     1.39      299MB     2.87    14    29      10.1s <NULL>
15 mod_l3        505.5ms 527.39ms     1.89      255MB     3.12    20    33      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    6.23s    6.37s     0.157    6.07GB    1.41      2    18      12.7s <NULL>
 2 mod_a_re        8.89s    9.06s     0.110    12.2GB    0.938     2    17      18.1s <NULL>
 3 mod_c2c         3.47s    3.48s     0.287    3.18GB    0.478     3     5      10.5s <NULL>
 4 mod_c2c2        2.75s    2.83s     0.353    3.44GB    0.618     4     7      11.3s <NULL>
 5 mod_c2c2vc      2.97s    3.03s     0.328    3.44GB    0.655     4     8      12.2s <NULL>
 6 mod_c2c2br      3.15s    3.25s     0.306    3.46GB    0.688     4     9      13.1s <NULL>
 7 mod_f           9.33s    9.36s     0.107    15.4GB    0.801     2    15      18.7s <NULL>
 8 mod_k           2.92s    3.15s     0.320     3.8GB    0.560     4     7      12.5s <NULL>
 9 mod_k2          2.41s    2.41s     0.413    2.71GB    0.579     5     7      12.1s <NULL>
10 mod_k3          2.17s    2.18s     0.458     2.4GB    0.458     5     5      10.9s <NULL>
11 mod_l           2.86s    2.87s     0.349    6.43GB    1.13      4    13      11.5s <NULL>
12 mod_l0          2.79s    2.82s     0.342    6.43GB    1.03      4    12      11.7s <NULL>
13 mod_l2          2.87s     2.9s     0.345    6.96GB    1.12      4    13      11.6s <NULL>
14 mod_l20         2.87s    2.88s     0.348    6.96GB    1.04      4    12      11.5s <NULL>
15 mod_l3          2.09s    2.12s     0.472    5.36GB    1.23      5    13      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del 778.72ms 808.88ms     1.23   410.26MB    0.945    13    10      10.6s <NULL>
 2 mod_a_re        1.41s    1.42s     0.704  961.74MB    0.704     8     8      11.4s <NULL>
 3 mod_c2c      732.93ms 759.32ms     1.30   398.12MB    0.839    14     9      10.7s <NULL>
 4 mod_c2c2     602.04ms 627.69ms     1.60   416.08MB    0.944    17    10      10.6s <NULL>
 5 mod_c2c2vc   672.45ms  704.9ms     1.39   437.81MB    1.02     15    11      10.8s <NULL>
 6 mod_c2c2br   747.29ms 781.96ms     1.28   441.19MB    1.08     13    11      10.2s <NULL>
 7 mod_f           1.86s    1.98s     0.508    1.26GB    1.10      6    13      11.8s <NULL>
 8 mod_k        600.95ms 647.05ms     1.55   459.15MB    0.873    16     9      10.3s <NULL>
 9 mod_k2       454.24ms 462.79ms     2.13    363.7MB    0.580    22     6      10.3s <NULL>
10 mod_k3       413.83ms 427.49ms     2.27   333.12MB    0.591    23     6      10.1s <NULL>
11 mod_l        491.68ms 506.25ms     1.93   531.54MB    0.675    20     7      10.4s <NULL>
12 mod_l0       494.49ms  504.1ms     1.94   531.54MB    0.775    20     8      10.3s <NULL>
13 mod_l2       476.74ms 493.51ms     1.92   543.23MB    0.674    20     7      10.4s <NULL>
14 mod_l20      484.17ms 489.58ms     2.00   543.23MB    0.699    20     7        10s <NULL>
15 mod_l3        411.9ms 417.45ms     2.36   477.86MB    0.688    24     7      10.2s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.48s     1.5s     0.663     245MB     1.90     7    20      10.6s <NULL>
 2 mod_a_re        2.17s     2.2s     0.455     662MB     1.64     5    18        11s <NULL>
 3 mod_c2c         1.24s    1.27s     0.779     292MB     1.85     8    19      10.3s <NULL>
 4 mod_c2c2     904.95ms 927.87ms     0.987     275MB     1.78    10    18      10.1s <NULL>
 5 mod_c2c2vc      1.12s    1.16s     0.863     288MB     2.01     9    21      10.4s <NULL>
 6 mod_c2c2br       1.3s    1.32s     0.757     297MB     2.08     8    22      10.6s <NULL>
 7 mod_f           3.34s    3.38s     0.296     763MB     1.97     3    20      10.1s <NULL>
 8 mod_k        940.66ms 973.47ms     1.03      283MB     1.78    11    19      10.7s <NULL>
 9 mod_k2       533.03ms 558.56ms     1.78      185MB     1.58    18    16      10.1s <NULL>
10 mod_k3       467.77ms 503.75ms     1.92      166MB     1.55    21    17        11s <NULL>
11 mod_l        647.68ms 658.35ms     1.52      288MB     1.71    16    18      10.5s <NULL>
12 mod_l0       654.85ms 669.96ms     1.48      288MB     1.67    15    17      10.2s <NULL>
13 mod_l2       667.65ms  679.8ms     1.46      299MB     1.75    15    18      10.3s <NULL>
14 mod_l20       676.8ms 687.28ms     1.45      299MB     1.73    15    18      10.4s <NULL>
15 mod_l3       508.77ms 535.29ms     1.86      255MB     1.76    19    18      10.2s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    7.24s    7.41s     0.135    6.07GB    0.945     2    14      14.8s <NULL>
 2 mod_a_re        9.64s    9.81s     0.102    12.2GB    1.17      2    23      19.6s <NULL>
 3 mod_c2c          3.7s     3.7s     0.270    3.18GB    0.450     3     5      11.1s <NULL>
 4 mod_c2c2        2.73s    2.77s     0.358    3.44GB    0.537     4     6      11.2s <NULL>
 5 mod_c2c2vc      2.94s    2.96s     0.331    3.44GB    0.661     4     8      12.1s <NULL>
 6 mod_c2c2br      3.09s     3.1s     0.318    3.46GB    0.636     4     8      12.6s <NULL>
 7 mod_f           9.04s    9.06s     0.110    15.4GB    0.827     2    15      18.1s <NULL>
 8 mod_k           2.85s    2.88s     0.348     3.8GB    0.609     4     7      11.5s <NULL>
 9 mod_k2          2.39s     2.4s     0.416    2.71GB    0.582     5     7        12s <NULL>
10 mod_k3          2.15s    2.16s     0.461     2.4GB    0.553     5     6      10.9s <NULL>
11 mod_l           2.83s    2.85s     0.351    6.43GB    0.965     4    11      11.4s <NULL>
12 mod_l0          2.85s    2.87s     0.349    6.43GB    1.05      4    12      11.5s <NULL>
13 mod_l2          2.92s    2.95s     0.339    6.96GB    1.10      4    13      11.8s <NULL>
14 mod_l20         2.92s    2.94s     0.339    6.96GB    1.10      4    13      11.8s <NULL>
15 mod_l3          2.17s    2.19s     0.441    5.36GB    1.06      5    12      11.3s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 15 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del 907.25ms 921.75ms     1.08   410.26MB    1.08     11    11      10.2s <NULL>
 2 mod_a_re        1.44s    1.54s     0.653  961.93MB    0.839     7     9      10.7s <NULL>
 3 mod_c2c      809.95ms 848.98ms     1.18   398.35MB    0.982    12    10      10.2s <NULL>
 4 mod_c2c2     650.02ms 695.08ms     1.46   415.82MB    1.07     15    11      10.3s <NULL>
 5 mod_c2c2vc   755.88ms 785.45ms     1.27   438.06MB    1.17     13    12      10.3s <NULL>
 6 mod_c2c2br    780.2ms 828.29ms     1.15   440.98MB    1.15     12    12      10.4s <NULL>
 7 mod_f           1.72s    1.78s     0.564    1.26GB    1.22      6    13      10.6s <NULL>
 8 mod_k        642.26ms 666.12ms     1.50   458.95MB    0.845    16     9      10.7s <NULL>
 9 mod_k2       446.37ms 493.98ms     2.02    363.7MB    0.482    21     5      10.4s <NULL>
10 mod_k3       414.38ms 454.27ms     2.20   333.12MB    0.575    23     6      10.4s <NULL>
11 mod_l        516.99ms 531.24ms     1.85   531.54MB    0.680    19     7      10.3s <NULL>
12 mod_l0       499.05ms 537.93ms     1.82   531.54MB    0.671    19     7      10.4s <NULL>
13 mod_l2       522.04ms 533.95ms     1.83   543.23MB    0.673    19     7      10.4s <NULL>
14 mod_l20      496.38ms 534.71ms     1.84   543.23MB    0.679    19     7      10.3s <NULL>
15 mod_l3       439.61ms 462.73ms     2.11   477.86MB    0.575    22     6      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 5

#+begin_quote
Setup 1
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.44s    1.46s     0.678     245MB     2.61     7    27      10.3s <NULL>
 2 mod_c2c         1.13s    1.17s     0.832     292MB     2.40     9    26      10.8s <NULL>
 3 mod_c2c2     918.52ms 947.47ms     1.04      275MB     2.37    11    25      10.5s <NULL>
 4 mod_c2c2vc      1.17s    1.18s     0.842     289MB     2.71     9    29      10.7s <NULL>
 5 mod_c2c2br       1.3s    1.31s     0.756     298MB     2.74     8    29      10.6s <NULL>
 6 mod_k        927.19ms 949.77ms     1.05      283MB     2.57    11    27      10.5s <NULL>
 7 mod_k2       629.34ms 663.74ms     1.46      185MB     2.24    15    23      10.3s <NULL>
 8 mod_k3       574.47ms 609.58ms     1.62      166MB     2.29    17    24      10.5s <NULL>
 9 mod_l        792.53ms 824.09ms     1.18      288MB     2.26    12    23      10.2s <NULL>
10 mod_l0       797.26ms 803.47ms     1.24      288MB     2.48    13    26      10.5s <NULL>
11 mod_l2       806.51ms 828.67ms     1.21      299MB     2.51    13    27      10.8s <NULL>
12 mod_l3       794.25ms 804.96ms     1.18      288MB     2.36    12    24      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    5.96s    6.05s     0.165    6.07GB    1.57      2    19      12.1s <NULL>
 2 mod_c2c         3.41s    3.42s     0.291    3.18GB    0.970     3    10      10.3s <NULL>
 3 mod_c2c2        2.74s    2.74s     0.363    3.44GB    0.998     4    11        11s <NULL>
 4 mod_c2c2vc      2.82s    2.84s     0.353    3.44GB    0.970     4    11      11.3s <NULL>
 5 mod_c2c2br         3s    3.08s     0.320    3.46GB    0.960     4    12      12.5s <NULL>
 6 mod_k           2.81s    2.83s     0.353     3.8GB    0.883     4    10      11.3s <NULL>
 7 mod_k2          2.51s    2.53s     0.395    2.71GB    0.790     4     8      10.1s <NULL>
 8 mod_k3          2.26s    2.29s     0.439     2.4GB    0.702     5     8      11.4s <NULL>
 9 mod_l           2.87s    2.92s     0.335    6.43GB    1.34      4    16      11.9s <NULL>
10 mod_l0          2.85s    2.85s     0.351    6.43GB    1.14      4    13      11.4s <NULL>
11 mod_l2          2.93s    2.95s     0.339    6.96GB    1.27      4    15      11.8s <NULL>
12 mod_l3           2.9s    2.93s     0.337    6.43GB    1.18      4    14      11.9s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    820ms    848ms      1.18     410MB    1.78     12    18      10.1s <NULL>
 2 mod_c2c         732ms    759ms      1.27     398MB    1.17     13    12      10.2s <NULL>
 3 mod_c2c2        577ms    600ms      1.67     416MB    1.28     17    13      10.2s <NULL>
 4 mod_c2c2vc      668ms    691ms      1.43     438MB    1.53     15    16      10.5s <NULL>
 5 mod_c2c2br      722ms    739ms      1.33     441MB    1.52     14    16      10.5s <NULL>
 6 mod_k           593ms    619ms      1.59     459MB    1.29     16    13      10.1s <NULL>
 7 mod_k2          502ms    527ms      1.90     364MB    0.951    20    10      10.5s <NULL>
 8 mod_k3          463ms    493ms      2.00     333MB    0.900    20     9        10s <NULL>
 9 mod_l           540ms    584ms      1.68     532MB    1.09     17    11      10.1s <NULL>
10 mod_l0          537ms    573ms      1.74     532MB    1.06     18    11      10.4s <NULL>
11 mod_l2          527ms    550ms      1.74     543MB    1.06     18    11      10.4s <NULL>
12 mod_l3          530ms    551ms      1.80     532MB    1.20     18    12        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.46s    1.47s     0.672     244MB     2.79     7    29      10.4s <NULL>
 2 mod_c2c         1.17s     1.2s     0.826     292MB     2.75     9    30      10.9s <NULL>
 3 mod_c2c2     987.03ms    1.03s     0.969     275MB     2.91    10    30      10.3s <NULL>
 4 mod_c2c2vc      1.13s    1.19s     0.813     288MB     2.62     9    29      11.1s <NULL>
 5 mod_c2c2br      1.25s    1.28s     0.777     298MB     2.82     8    29      10.3s <NULL>
 6 mod_k        924.43ms  946.2ms     1.05      283MB     2.49    11    26      10.4s <NULL>
 7 mod_k2       676.32ms 712.84ms     1.40      185MB     2.29    14    23        10s <NULL>
 8 mod_k3       621.25ms 648.52ms     1.52      166MB     2.19    16    23      10.5s <NULL>
 9 mod_l         772.7ms 785.38ms     1.21      288MB     2.33    13    25      10.8s <NULL>
10 mod_l0       776.53ms 795.23ms     1.26      288MB     2.41    13    25      10.4s <NULL>
11 mod_l2       797.88ms 864.45ms     1.14      299MB     2.28    12    24      10.5s <NULL>
12 mod_l3       819.86ms  858.8ms     1.15      288MB     2.29    12    24      10.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    7.11s    7.17s     0.139    6.07GB    1.32      2    19      14.3s <NULL>
 2 mod_c2c         3.72s    3.73s     0.268    3.18GB    1.07      3    12      11.2s <NULL>
 3 mod_c2c2        2.79s    2.81s     0.356    3.44GB    1.34      4    15      11.2s <NULL>
 4 mod_c2c2vc      2.87s    2.89s     0.344    3.44GB    1.20      4    14      11.6s <NULL>
 5 mod_c2c2br      3.05s    3.07s     0.326    3.46GB    1.14      4    14      12.3s <NULL>
 6 mod_k           2.88s    2.92s     0.343     3.8GB    1.29      4    15      11.7s <NULL>
 7 mod_k2          2.69s    2.85s     0.349    2.71GB    0.960     4    11      11.5s <NULL>
 8 mod_k3          2.52s    2.59s     0.387     2.4GB    0.871     4     9      10.3s <NULL>
 9 mod_l           3.26s    3.33s     0.292    6.43GB    1.56      3    16      10.3s <NULL>
10 mod_l0          3.09s    3.14s     0.319    6.43GB    0.877     4    11      12.5s <NULL>
11 mod_l2          3.16s    3.22s     0.311    6.96GB    0.932     4    12      12.9s <NULL>
12 mod_l3          3.16s    3.21s     0.312    6.43GB    0.858     4    11      12.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 12 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    904ms    941ms      1.03     410MB    1.60     11    17      10.6s <NULL>
 2 mod_c2c         809ms    821ms      1.20     398MB    1.39     13    15      10.8s <NULL>
 3 mod_c2c2        629ms    659ms      1.43     416MB    1.14     15    12      10.5s <NULL>
 4 mod_c2c2vc      670ms    710ms      1.40     438MB    1.49     15    16      10.7s <NULL>
 5 mod_c2c2br      762ms    777ms      1.28     441MB    1.48     13    15      10.1s <NULL>
 6 mod_k           627ms    671ms      1.48     459MB    1.19     15    12      10.1s <NULL>
 7 mod_k2          517ms    573ms      1.74     364MB    0.870    18     9      10.3s <NULL>
 8 mod_k3          496ms    512ms      1.91     333MB    0.859    20     9      10.5s <NULL>
 9 mod_l           569ms    605ms      1.67     532MB    1.08     17    11      10.2s <NULL>
10 mod_l0          572ms    614ms      1.64     532MB    1.06     17    11      10.3s <NULL>
11 mod_l2          591ms    618ms      1.60     543MB    0.997    16    10        10s <NULL>
12 mod_l3          584ms    647ms      1.53     532MB    1.05     16    11      10.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 

#+end_quote

* partial 4

#+begin_quote
Setup 1
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.37s    1.39s     0.685     244MB     2.84     7    29      10.2s <NULL>
2 mod_c2c         1.13s    1.15s     0.849     292MB     2.64     9    28      10.6s <NULL>
3 mod_c2c2     932.04ms 956.86ms     1.04      275MB     2.93    11    31      10.6s <NULL>
4 mod_c2c2vc      1.16s    1.19s     0.839     289MB     3.08     9    33      10.7s <NULL>
5 mod_c2c2br      1.22s    1.25s     0.771     298MB     3.18     8    33      10.4s <NULL>
6 mod_k        898.66ms 913.16ms     1.09      283MB     3.07    11    31      10.1s <NULL>
7 mod_k2       639.39ms 661.35ms     1.52      185MB     2.75    16    29      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    6.23s    6.45s     0.155    6.07GB    1.47      2    19      12.9s <NULL>
2 mod_c2c          3.4s    3.44s     0.292    3.18GB    0.680     3     7      10.3s <NULL>
3 mod_c2c2        2.71s    2.71s     0.369    3.44GB    0.922     4    10      10.8s <NULL>
4 mod_c2c2vc      2.81s    2.96s     0.337    3.44GB    0.927     4    11      11.9s <NULL>
5 mod_c2c2br      3.12s    3.21s     0.310    3.46GB    1.08      4    14      12.9s <NULL>
6 mod_k           2.98s    3.13s     0.320     3.8GB    0.800     4    10      12.5s <NULL>
7 mod_k2          2.68s    2.79s     0.361    2.71GB    0.723     4     8      11.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    798ms    811ms      1.23     410MB     1.80    13    19      10.6s <NULL>
2 mod_c2c         726ms    742ms      1.30     399MB     1.40    13    14        10s <NULL>
3 mod_c2c2        592ms    608ms      1.63     416MB     1.53    17    16      10.4s <NULL>
4 mod_c2c2vc      675ms    706ms      1.41     438MB     1.88    15    20      10.6s <NULL>
5 mod_c2c2br      733ms    759ms      1.29     441MB     1.88    13    19      10.1s <NULL>
6 mod_k           656ms    688ms      1.45     459MB     1.45    15    15      10.4s <NULL>
7 mod_k2          501ms    552ms      1.79     364MB     1.09    18    11      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.55s    1.61s     0.614     245MB     2.72     7    31      11.4s <NULL>
2 mod_c2c         1.14s    1.18s     0.811     293MB     2.61     9    29      11.1s <NULL>
3 mod_c2c2     932.62ms 957.15ms     1.02      275MB     2.87    11    31      10.8s <NULL>
4 mod_c2c2vc      1.17s    1.19s     0.839     289MB     3.08     9    33      10.7s <NULL>
5 mod_c2c2br      1.33s    1.39s     0.718     297MB     3.05     8    34      11.1s <NULL>
6 mod_k        911.01ms 988.73ms     0.993     283MB     2.78    10    28      10.1s <NULL>
7 mod_k2       656.68ms 688.66ms     1.44      185MB     2.59    15    27      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    7.94s    8.06s     0.124    6.07GB    1.24      2    20      16.1s <NULL>
2 mod_c2c         3.81s    3.83s     0.257    3.18GB    0.770     3     9      11.7s <NULL>
3 mod_c2c2        2.74s    2.77s     0.358    3.44GB    1.08      4    12      11.2s <NULL>
4 mod_c2c2vc      2.88s    3.01s     0.327    3.44GB    0.980     4    12      12.2s <NULL>
5 mod_c2c2br      3.04s    3.21s     0.313    3.46GB    1.09      4    14      12.8s <NULL>
6 mod_k           2.82s    2.89s     0.337     3.8GB    1.10      4    13      11.9s <NULL>
7 mod_k2          2.59s    2.62s     0.372    2.71GB    0.837     4     9      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    913ms    1.01s     0.962     410MB     1.44    10    15      10.4s <NULL>
2 mod_c2c         778ms 812.24ms     1.23      398MB     1.23    13    13      10.6s <NULL>
3 mod_c2c2        630ms 650.19ms     1.53      416MB     1.44    16    15      10.4s <NULL>
4 mod_c2c2vc      714ms 737.98ms     1.34      438MB     1.62    14    17      10.5s <NULL>
5 mod_c2c2br      751ms 797.43ms     1.26      441MB     1.84    13    19      10.4s <NULL>
6 mod_k           665ms  678.5ms     1.46      459MB     1.37    15    14      10.3s <NULL>
7 mod_k2          505ms 556.12ms     1.79      364MB     1.19    18    12        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 3

#+begin_quote
Setup 1
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.48s    1.55s     0.649     245MB     3.15     7    34      10.8s <NULL>
2 mod_c2c         1.15s    1.18s     0.832     292MB     3.05     9    33      10.8s <NULL>
3 mod_c2c2     895.01ms 976.02ms     1.01      275MB     3.12    11    34      10.9s <NULL>
4 mod_c2c2vc      1.09s    1.12s     0.889     289MB     3.26     9    33      10.1s <NULL>
5 mod_c2c2br      1.27s    1.29s     0.773     297MB     3.19     8    33      10.4s <NULL>
6 mod_k        932.44ms 959.37ms     1.02      283MB     2.88    11    31      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    6.16s    6.35s     0.157    6.07GB    1.57      2    20      12.7s <NULL>
2 mod_c2c         3.49s    3.56s     0.283    3.18GB    0.753     3     8      10.6s <NULL>
3 mod_c2c2        2.86s    2.96s     0.334    3.44GB    0.920     4    11        12s <NULL>
4 mod_c2c2vc         3s    3.15s     0.319    3.44GB    0.958     4    12      12.5s <NULL>
5 mod_c2c2br      3.11s    3.32s     0.306    3.46GB    1.07      4    14      13.1s <NULL>
6 mod_k           2.94s    2.99s     0.334     3.8GB    1.00      4    12        12s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    858ms    884ms      1.10     410MB     1.70    11    17        10s <NULL>
2 mod_c2c         739ms    761ms      1.28     398MB     1.28    13    13      10.1s <NULL>
3 mod_c2c2        593ms    605ms      1.65     416MB     1.56    17    16      10.3s <NULL>
4 mod_c2c2vc      680ms    694ms      1.43     438MB     1.72    15    18      10.5s <NULL>
5 mod_c2c2br      727ms    767ms      1.29     441MB     1.88    13    19      10.1s <NULL>
6 mod_k           619ms    640ms      1.55     459MB     1.45    16    15      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.49s    1.53s     0.650     245MB     3.34     7    36      10.8s <NULL>
2 mod_c2c         1.22s    1.26s     0.791     292MB     3.26     8    33      10.1s <NULL>
3 mod_c2c2      922.6ms 946.62ms     0.984     275MB     2.95    10    30      10.2s <NULL>
4 mod_c2c2vc      1.13s    1.18s     0.837     289MB     2.98     9    32      10.8s <NULL>
5 mod_c2c2br      1.42s    1.44s     0.692     297MB     2.97     7    30      10.1s <NULL>
6 mod_k              1s    1.04s     0.957     283MB     2.68    10    28      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    7.49s     7.9s     0.127    6.07GB    1.08      2    17      15.8s <NULL>
2 mod_c2c         3.67s    3.67s     0.271    3.18GB    0.722     3     8      11.1s <NULL>
3 mod_c2c2        2.71s    2.72s     0.368    3.44GB    0.827     4     9      10.9s <NULL>
4 mod_c2c2vc      2.87s    2.91s     0.345    3.44GB    0.947     4    11      11.6s <NULL>
5 mod_c2c2br      3.12s    3.22s     0.310    3.46GB    1.09      4    14      12.9s <NULL>
6 mod_k           2.81s    2.87s     0.347     3.8GB    0.781     4     9      11.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    895ms    919ms      1.08     410MB     1.67    11    17      10.2s <NULL>
2 mod_c2c         706ms    794ms      1.23     398MB     1.42    13    15      10.6s <NULL>
3 mod_c2c2        597ms    626ms      1.59     416MB     1.49    16    15        10s <NULL>
4 mod_c2c2vc      674ms    719ms      1.39     438MB     1.69    14    17        10s <NULL>
5 mod_c2c2br      760ms    789ms      1.26     441MB     1.74    13    18      10.3s <NULL>
6 mod_k           633ms    664ms      1.50     459MB     1.40    15    14        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 2

#+begin_quote
Setup 1
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.36s  1.54s     0.646     245MB     3.97     7    43      10.8s <NULL>
2 mod_a                2.01s  2.05s     0.488     662MB     2.83     5    29      10.3s <NULL>
3 mod_a_re             2.01s  2.04s     0.489     663MB     2.74     5    28      10.2s <NULL>
4 mod_c                1.39s  1.41s     0.700     279MB     2.71     8    31      11.4s <NULL>
5 mod_c2c              1.13s  1.21s     0.811     292MB     2.88     9    32      11.1s <NULL>
6 mod_c_delta_d_del    1.61s  1.64s     0.609     314MB     3.22     7    37      11.5s <NULL>
7 mod_h                 1.6s  1.63s     0.603     382MB     3.62     7    42      11.6s <NULL>
8 mod_h2               1.69s  1.71s     0.586     391MB     3.61     6    37      10.2s <NULL>
9 mod_i                 1.5s  1.52s     0.634     326MB     2.90     7    32        11s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.58s   6.9s     0.145    6.07GB    1.74      2    24      13.8s <NULL>
2 mod_a                9.04s  9.28s     0.108    12.2GB    0.862     2    16      18.6s <NULL>
3 mod_a_re              9.4s  9.44s     0.106    12.2GB    0.900     2    17      18.9s <NULL>
4 mod_c                6.14s  6.19s     0.162    2.33GB    0.485     2     6      12.4s <NULL>
5 mod_c2c              3.88s  4.42s     0.233    3.18GB    0.698     3     9      12.9s <NULL>
6 mod_c_delta_d_del    6.91s     7s     0.143    3.16GB    0.714     2    10        14s <NULL>
7 mod_h                4.79s  4.99s     0.201    4.59GB    0.872     3    13      14.9s <NULL>
8 mod_h2               4.46s  4.95s     0.209     4.6GB    1.04      3    15      14.4s <NULL>
9 mod_i                6.16s   6.2s     0.161    3.51GB    0.565     2     7      12.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 9 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    900.55ms 920.98ms     1.07      410MB     1.85    11    19      10.3s <NULL>
2 mod_a              1.48s     1.6s     0.621     962MB     1.33     7    15      11.3s <NULL>
3 mod_a_re           1.41s    1.47s     0.658     962MB     1.41     7    15      10.6s <NULL>
4 mod_c           932.85ms 954.82ms     1.02      336MB     1.48    11    16      10.8s <NULL>
5 mod_c2c         733.78ms 742.11ms     1.34      398MB     1.44    14    15      10.4s <NULL>
6 mod_c_delta_d_… 998.11ms    1.07s     0.929     416MB     1.49    10    16      10.8s <NULL>
7 mod_h           925.79ms 963.71ms     1.04      534MB     1.89    11    20      10.6s <NULL>
8 mod_h2           948.9ms    1.07s     0.952     537MB     1.81    10    19      10.5s <NULL>
9 mod_i              1.16s    1.24s     0.814     455MB     1.18     9    13      11.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.46s  1.56s     0.629     245MB     3.51     7    39      11.1s <NULL>
2 mod_a                2.12s  2.19s     0.449     662MB     2.52     5    28      11.1s <NULL>
3 mod_a_re             2.12s  2.18s     0.457     663MB     2.65     5    29      10.9s <NULL>
4 mod_c                1.45s  1.53s     0.651     280MB     2.51     7    27      10.8s <NULL>
5 mod_c2c              1.16s   1.2s     0.794     292MB     2.88     8    29      10.1s <NULL>
6 mod_c_delta_d_del    1.76s  1.79s     0.555     314MB     2.87     6    31      10.8s <NULL>
7 mod_h                 1.7s  1.71s     0.578     382MB     3.47     6    36      10.4s <NULL>
8 mod_h2               1.74s  1.78s     0.561     391MB     3.46     6    37      10.7s <NULL>
9 mod_i                1.52s  1.56s     0.616     326MB     2.82     7    32      11.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         7.87s  8.05s    0.124     6.07GB    1.30      2    21      16.1s <NULL>
2 mod_a               10.88s 10.88s    0.0919    12.2GB    0.643     1     7      10.9s <NULL>
3 mod_a_re            10.11s 10.11s    0.0989    12.2GB    0.594     1     6      10.1s <NULL>
4 mod_c                7.09s  7.27s    0.137     2.33GB    0.481     2     7      14.5s <NULL>
5 mod_c2c              3.74s  3.84s    0.257     3.18GB    0.685     3     8      11.7s <NULL>
6 mod_c_delta_d_del    7.43s  7.44s    0.134     3.16GB    0.672     2    10      14.9s <NULL>
7 mod_h                4.37s  4.39s    0.226     4.59GB    0.978     3    13      13.3s <NULL>
8 mod_h2               4.75s  4.77s    0.206      4.6GB    1.03      3    15      14.6s <NULL>
9 mod_i                7.01s  7.12s    0.141     3.51GB    0.492     2     7      14.2s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 9 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del       1.01s    1.04s     0.955     410MB     1.53    10    16      10.5s <NULL>
2 mod_a              1.73s    1.75s     0.570     962MB     1.24     6    13      10.5s <NULL>
3 mod_a_re           1.57s    1.67s     0.603     962MB     1.21     7    14      11.6s <NULL>
4 mod_c              1.13s    1.16s     0.838     336MB     1.12     9    12      10.7s <NULL>
5 mod_c2c         844.59ms 882.31ms     1.09      398MB     1.38    11    14      10.1s <NULL>
6 mod_c_delta_d_…    1.21s    1.32s     0.755     416MB     1.42     8    15      10.6s <NULL>
7 mod_h           985.65ms    1.02s     0.967     535MB     1.74    10    18      10.3s <NULL>
8 mod_h2             1.04s     1.1s     0.904     538MB     1.63    10    18      11.1s <NULL>
9 mod_i              1.28s    1.31s     0.757     455MB     1.04     8    11      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial

#+begin_quote
orig/alt

 1 lgmem_no_del 502ms  519ms      1.89        NA     2.49    19    25      10.1s <NULL> <NULL>
 2 mod_a        707ms  737ms      1.36        NA     2.14    14    22      10.3s <NULL> <NULL>
 3 mod_a_re     638ms  659ms      1.47        NA     2.06    15    21      10.2s <NULL> <NULL>
 5 mod_c        463ms  482ms      2.07        NA     1.87    21    19      10.1s <NULL> <NULL>
12 mod_h        552ms  563ms      1.77        NA     2.46    18    25      10.2s <NULL> <NULL>
13 mod_h2       570ms  611ms      1.59        NA     2.39    16    24      10.1s <NULL> <NULL>
15 mod_i        520ms  537ms      1.85        NA     2.04    19    21      10.3s <NULL> <NULL>

alt/orig

 1 lgmem_no_d…  1.81s   1.9s    0.524         NA    2.27      6    26      11.4s <NULL> <NULL>
 2 mod_a           3s  3.19s    0.315         NA    2.68      4    34      12.7s <NULL> <NULL>
 3 mod_a_re     2.93s     3s    0.333         NA    1.08      4    13        12s <NULL> <NULL>
 5 mod_c        1.98s  1.99s    0.503         NA    0.503     6     6      11.9s <NULL> <NULL>
12 mod_h        1.38s  1.43s    0.686         NA    0.979     7    10      10.2s <NULL> <NULL>
13 mod_h2       1.38s  1.48s    0.673         NA    0.961     7    10      10.4s <NULL> <NULL>
15 mod_i        1.96s  1.98s    0.503         NA    0.503     6     6      11.9s <NULL> <NULL>

lger fewer

 1 lgmem_no_del   868.75ms  930.3ms     1.08         NA    1.37     11    14      10.2s <NULL>
 2 mod_a             1.48s    1.49s     0.657        NA    1.13      7    12      10.7s <NULL>
 3 mod_a_re          1.46s     1.5s     0.670        NA    1.24      7    13      10.4s <NULL>
 5 mod_c          971.21ms    1.02s     0.977        NA    0.879    10     9      10.2s <NULL>
12 mod_h          964.61ms 993.91ms     0.982        NA    1.47     10    15      10.2s <NULL>
13 mod_h2         982.86ms 995.44ms     1.00         NA    1.55     11    17        11s <NULL>
15 mod_i             1.19s    1.33s     0.732        NA    0.824     8     9      10.9s <NULL>

lger fewer DTthreads(1)

 1 lgmem_no_del   954.74ms 966.33ms     1.03         NA    1.32     11    14      10.6s <NULL>
 2 mod_a             1.57s    1.58s     0.628        NA    1.35      7    15      11.1s <NULL>
 3 mod_a_re          1.51s    1.54s     0.636        NA    1.18      7    13        11s <NULL>
 5 mod_c             1.06s    1.12s     0.895        NA    0.795     9     8      10.1s <NULL>
12 mod_h             1.03s    1.04s     0.951        NA    1.43     10    15      10.5s <NULL>
13 mod_h2            1.02s    1.06s     0.941        NA    1.41     10    15      10.6s <NULL>
15 mod_i             1.19s    1.23s     0.806        NA    0.895     9    10      11.2s <NULL>
#+end_quote

seems like h approaches probably best balanced?

* a bit more systematic

#+begin_src r
setups <- tribble(
  ~snaps, ~DTthreads,
  snapshots, 6,
  alt_snapshots, 6,
  larger_fewer_snapshots, 6,
  snapshots, 1,
  alt_snapshots, 1,
  larger_fewer_snapshots, 1,
  )
#+end_src

#+begin_quote
Setup 1
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.47s  1.49s     0.652     245MB     3.17     7    34      10.7s <NULL>
2 mod_a                2.09s   2.1s     0.477     663MB     2.10     5    22      10.5s <NULL>
3 mod_a_re             2.05s   2.1s     0.476     662MB     2.00     5    21      10.5s <NULL>
4 mod_c                1.42s  1.44s     0.690     279MB     1.97     7    20      10.1s <NULL>
5 mod_c_delta_d_del    1.66s  1.73s     0.569     314MB     2.18     6    23      10.5s <NULL>
6 mod_h                 1.6s  1.62s     0.611     382MB     2.70     7    31      11.5s <NULL>
7 mod_h2               1.66s  1.68s     0.594     391MB     2.67     6    27      10.1s <NULL>
8 mod_i                1.59s  1.62s     0.615     326MB     2.20     7    25      11.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.12s  6.27s     0.160    6.07GB    1.36      2    17      12.5s <NULL>
2 mod_a                8.75s  9.16s     0.109    12.2GB    0.710     2    13      18.3s <NULL>
3 mod_a_re             9.35s  9.54s     0.105    12.2GB    0.733     2    14      19.1s <NULL>
4 mod_c                6.36s  6.38s     0.157    2.33GB    0.392     2     5      12.8s <NULL>
5 mod_c_delta_d_del    6.38s  6.41s     0.156    3.16GB    0.546     2     7      12.8s <NULL>
6 mod_h                4.19s  4.29s     0.235    4.59GB    0.782     3    10      12.8s <NULL>
7 mod_h2               4.31s  4.37s     0.229     4.6GB    0.839     3    11      13.1s <NULL>
8 mod_i                6.01s  6.05s     0.165    3.51GB    0.496     2     6      12.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 8 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    815.32ms 829.21ms     1.20      411MB    1.50     12    15        10s <NULL>
2 mod_a              1.43s    1.44s     0.694     962MB    0.991     7    10      10.1s <NULL>
3 mod_a_re            1.4s    1.45s     0.690     962MB    0.986     7    10      10.1s <NULL>
4 mod_c           941.92ms 954.45ms     1.05      336MB    1.05     11    11      10.5s <NULL>
5 mod_c_delta_d_…    1.04s    1.06s     0.925     416MB    1.20     10    13      10.8s <NULL>
6 mod_h           956.62ms 978.26ms     1.01      534MB    1.56     11    17      10.9s <NULL>
7 mod_h2          974.15ms 992.94ms     1.00      538MB    1.55     11    17        11s <NULL>
8 mod_i              1.11s    1.16s     0.860     455MB    0.956     9    10      10.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.51s  1.52s     0.655     245MB     2.53     7    27      10.7s <NULL>
2 mod_a                2.17s  2.17s     0.459     663MB     2.29     5    25      10.9s <NULL>
3 mod_a_re             2.17s  2.18s     0.457     662MB     2.19     5    24      10.9s <NULL>
4 mod_c                 1.4s   1.5s     0.647     280MB     2.03     7    22      10.8s <NULL>
5 mod_c_delta_d_del    1.69s  1.69s     0.586     314MB     2.34     6    24      10.2s <NULL>
6 mod_h                1.63s  1.66s     0.598     382MB     2.69     6    27        10s <NULL>
7 mod_h2               1.69s  1.72s     0.579     391MB     2.61     6    27      10.4s <NULL>
8 mod_i                1.64s  1.68s     0.597     326MB     2.22     7    26      11.7s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.94s  7.24s     0.138    6.07GB    1.31      2    19      14.5s <NULL>
2 mod_a                 9.7s  9.84s     0.102    12.2GB    1.07      2    21      19.7s <NULL>
3 mod_a_re              9.6s   9.6s     0.104    12.2GB    0.677     2    13      19.2s <NULL>
4 mod_c                 6.6s  6.65s     0.150    2.33GB    0.376     2     5      13.3s <NULL>
5 mod_c_delta_d_del    6.93s  6.96s     0.144    3.16GB    0.503     2     7      13.9s <NULL>
6 mod_h                4.31s  4.32s     0.232    4.59GB    0.849     3    11      12.9s <NULL>
7 mod_h2               4.34s   4.4s     0.227     4.6GB    0.758     3    10      13.2s <NULL>
8 mod_i                 6.6s  6.64s     0.151    3.51GB    0.452     2     6      13.3s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 8 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    938.69ms 951.99ms     1.05      410MB    1.24     11    13      10.5s <NULL>
2 mod_a              1.53s    1.55s     0.640     962MB    1.01      7    11      10.9s <NULL>
3 mod_a_re           1.51s    1.52s     0.655     962MB    0.936     7    10      10.7s <NULL>
4 mod_c              1.05s    1.07s     0.924     336MB    0.924    10    10      10.8s <NULL>
5 mod_c_delta_d_…    1.13s    1.15s     0.872     416MB    1.16      9    12      10.3s <NULL>
6 mod_h              1.02s    1.06s     0.940     534MB    1.41     10    15      10.6s <NULL>
7 mod_h2             1.03s    1.06s     0.940     538MB    1.41     10    15      10.6s <NULL>
8 mod_i              1.17s     1.2s     0.834     455MB    1.02      9    11      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

