* partial 5

#+begin_quote
Setup 1
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.53s     1.6s     0.621     245MB     3.01     7    34      11.3s <NULL>
 2 mod_c2c         1.22s    1.24s     0.800     292MB     3.02     9    34      11.3s <NULL>
 3 mod_c2c2     949.71ms 987.02ms     0.965     275MB     2.80    10    29      10.4s <NULL>
 4 mod_c2c2vc      1.17s    1.28s     0.788     289MB     2.96     8    30      10.1s <NULL>
 5 mod_c2c2br      1.35s    1.41s     0.692     297MB     3.06     7    31      10.1s <NULL>
 6 mod_k        982.61ms       1s     0.996     283MB     2.99    10    30        10s <NULL>
 7 mod_k2       649.63ms 664.22ms     1.42      185MB     2.66    15    28      10.5s <NULL>
 8 mod_k3       658.06ms  667.9ms     1.48      185MB     2.77    15    28      10.1s <NULL>
 9 mod_l        657.02ms 668.38ms     1.48      185MB     2.87    15    29      10.1s <NULL>
10 mod_l0       664.55ms 672.19ms     1.48      185MB     2.87    15    29      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    6.52s    6.72s     0.149    6.07GB    1.26      2    17      13.4s <NULL>
 2 mod_c2c         3.75s    3.75s     0.265    3.18GB    0.706     3     8      11.3s <NULL>
 3 mod_c2c2        2.95s    2.98s     0.335    3.44GB    0.755     4     9      11.9s <NULL>
 4 mod_c2c2vc      3.07s    3.08s     0.325    3.44GB    0.974     4    12      12.3s <NULL>
 5 mod_c2c2br      3.23s    3.27s     0.306    3.46GB    1.07      4    14      13.1s <NULL>
 6 mod_k           2.99s    3.04s     0.330     3.8GB    0.907     4    11      12.1s <NULL>
 7 mod_k2          2.64s    2.64s     0.378    2.71GB    0.662     4     7      10.6s <NULL>
 8 mod_k3          2.64s    2.66s     0.376    2.71GB    0.658     4     7      10.6s <NULL>
 9 mod_l           2.58s    2.63s     0.371    2.71GB    0.649     4     7      10.8s <NULL>
10 mod_l0          2.56s    2.61s     0.385    2.71GB    0.578     4     6      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    865ms    884ms      1.13     410MB     1.89    12    20      10.6s <NULL>
 2 mod_c2c         773ms    792ms      1.26     398MB     1.56    13    16      10.3s <NULL>
 3 mod_c2c2        632ms    641ms      1.55     416MB     1.75    16    18      10.3s <NULL>
 4 mod_c2c2vc      711ms    737ms      1.35     438MB     2.03    14    21      10.3s <NULL>
 5 mod_c2c2br      739ms    750ms      1.28     441MB     1.87    13    19      10.2s <NULL>
 6 mod_k           622ms    631ms      1.57     459MB     1.48    16    15      10.2s <NULL>
 7 mod_k2          516ms    573ms      1.74     364MB     1.06    18    11      10.3s <NULL>
 8 mod_k3          516ms    554ms      1.77     364MB     1.08    18    11      10.2s <NULL>
 9 mod_l           508ms    535ms      1.85     364MB     1.17    19    12      10.3s <NULL>
10 mod_l0          511ms    532ms      1.88     364MB     1.19    19    12      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    1.62s    1.64s     0.609     244MB     2.96     7    34      11.5s <NULL>
 2 mod_c2c         1.28s     1.3s     0.752     292MB     2.73     8    29      10.6s <NULL>
 3 mod_c2c2     962.43ms 987.12ms     1.01      275MB     2.94    11    32      10.9s <NULL>
 4 mod_c2c2vc      1.18s    1.23s     0.815     289MB     3.08     9    34        11s <NULL>
 5 mod_c2c2br      1.39s     1.4s     0.715     298MB     3.13     8    35      11.2s <NULL>
 6 mod_k        915.04ms    1.01s     0.975     284MB     2.83    10    29      10.3s <NULL>
 7 mod_k2       657.34ms  671.8ms     1.48      185MB     2.76    15    28      10.1s <NULL>
 8 mod_k3       663.55ms 678.23ms     1.47      185MB     2.75    15    28      10.2s <NULL>
 9 mod_l        673.78ms 688.96ms     1.45      185MB     2.79    15    29      10.4s <NULL>
10 mod_l0       687.05ms 693.79ms     1.44      185MB     2.78    15    29      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    7.57s    7.63s     0.131    6.07GB    1.31      2    20      15.3s <NULL>
 2 mod_c2c         3.96s    4.05s     0.246    3.18GB    0.739     3     9      12.2s <NULL>
 3 mod_c2c2        2.91s    2.93s     0.340    3.44GB    0.851     4    10      11.8s <NULL>
 4 mod_c2c2vc      2.99s       3s     0.330    3.44GB    0.908     4    11      12.1s <NULL>
 5 mod_c2c2br      3.22s    3.28s     0.306    3.46GB    1.07      4    14      13.1s <NULL>
 6 mod_k           3.02s    3.04s     0.329     3.8GB    0.904     4    11      12.2s <NULL>
 7 mod_k2          2.64s    2.66s     0.375    2.71GB    0.563     4     6      10.7s <NULL>
 8 mod_k3          2.62s    2.67s     0.375    2.71GB    0.657     4     7      10.7s <NULL>
 9 mod_l           2.63s    2.68s     0.374    2.71GB    0.654     4     7      10.7s <NULL>
10 mod_l0          2.66s    2.71s     0.368    2.71GB    0.643     4     7      10.9s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 10 × 13
   expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
 1 lgmem_no_del    950ms    995ms     0.980     410MB     1.47    10    15      10.2s <NULL>
 2 mod_c2c         820ms    828ms     1.21      398MB     1.30    13    14      10.8s <NULL>
 3 mod_c2c2        661ms    691ms     1.44      416MB     1.34    15    14      10.4s <NULL>
 4 mod_c2c2vc      744ms    777ms     1.29      438MB     1.59    13    16      10.1s <NULL>
 5 mod_c2c2br      804ms    839ms     1.19      441MB     1.78    12    18      10.1s <NULL>
 6 mod_k           676ms    695ms     1.43      459MB     1.34    15    14      10.5s <NULL>
 7 mod_k2          559ms    599ms     1.68      364MB     1.08    17    11      10.1s <NULL>
 8 mod_k3          560ms    585ms     1.71      364MB     1.05    18    11      10.5s <NULL>
 9 mod_l           567ms    597ms     1.68      364MB     1.08    17    11      10.1s <NULL>
10 mod_l0          560ms    594ms     1.66      364MB     1.11    18    12      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 4

#+begin_quote
Setup 1
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.37s    1.39s     0.685     244MB     2.84     7    29      10.2s <NULL>
2 mod_c2c         1.13s    1.15s     0.849     292MB     2.64     9    28      10.6s <NULL>
3 mod_c2c2     932.04ms 956.86ms     1.04      275MB     2.93    11    31      10.6s <NULL>
4 mod_c2c2vc      1.16s    1.19s     0.839     289MB     3.08     9    33      10.7s <NULL>
5 mod_c2c2br      1.22s    1.25s     0.771     298MB     3.18     8    33      10.4s <NULL>
6 mod_k        898.66ms 913.16ms     1.09      283MB     3.07    11    31      10.1s <NULL>
7 mod_k2       639.39ms 661.35ms     1.52      185MB     2.75    16    29      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    6.23s    6.45s     0.155    6.07GB    1.47      2    19      12.9s <NULL>
2 mod_c2c          3.4s    3.44s     0.292    3.18GB    0.680     3     7      10.3s <NULL>
3 mod_c2c2        2.71s    2.71s     0.369    3.44GB    0.922     4    10      10.8s <NULL>
4 mod_c2c2vc      2.81s    2.96s     0.337    3.44GB    0.927     4    11      11.9s <NULL>
5 mod_c2c2br      3.12s    3.21s     0.310    3.46GB    1.08      4    14      12.9s <NULL>
6 mod_k           2.98s    3.13s     0.320     3.8GB    0.800     4    10      12.5s <NULL>
7 mod_k2          2.68s    2.79s     0.361    2.71GB    0.723     4     8      11.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    798ms    811ms      1.23     410MB     1.80    13    19      10.6s <NULL>
2 mod_c2c         726ms    742ms      1.30     399MB     1.40    13    14        10s <NULL>
3 mod_c2c2        592ms    608ms      1.63     416MB     1.53    17    16      10.4s <NULL>
4 mod_c2c2vc      675ms    706ms      1.41     438MB     1.88    15    20      10.6s <NULL>
5 mod_c2c2br      733ms    759ms      1.29     441MB     1.88    13    19      10.1s <NULL>
6 mod_k           656ms    688ms      1.45     459MB     1.45    15    15      10.4s <NULL>
7 mod_k2          501ms    552ms      1.79     364MB     1.09    18    11      10.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.55s    1.61s     0.614     245MB     2.72     7    31      11.4s <NULL>
2 mod_c2c         1.14s    1.18s     0.811     293MB     2.61     9    29      11.1s <NULL>
3 mod_c2c2     932.62ms 957.15ms     1.02      275MB     2.87    11    31      10.8s <NULL>
4 mod_c2c2vc      1.17s    1.19s     0.839     289MB     3.08     9    33      10.7s <NULL>
5 mod_c2c2br      1.33s    1.39s     0.718     297MB     3.05     8    34      11.1s <NULL>
6 mod_k        911.01ms 988.73ms     0.993     283MB     2.78    10    28      10.1s <NULL>
7 mod_k2       656.68ms 688.66ms     1.44      185MB     2.59    15    27      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    7.94s    8.06s     0.124    6.07GB    1.24      2    20      16.1s <NULL>
2 mod_c2c         3.81s    3.83s     0.257    3.18GB    0.770     3     9      11.7s <NULL>
3 mod_c2c2        2.74s    2.77s     0.358    3.44GB    1.08      4    12      11.2s <NULL>
4 mod_c2c2vc      2.88s    3.01s     0.327    3.44GB    0.980     4    12      12.2s <NULL>
5 mod_c2c2br      3.04s    3.21s     0.313    3.46GB    1.09      4    14      12.8s <NULL>
6 mod_k           2.82s    2.89s     0.337     3.8GB    1.10      4    13      11.9s <NULL>
7 mod_k2          2.59s    2.62s     0.372    2.71GB    0.837     4     9      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 7 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    913ms    1.01s     0.962     410MB     1.44    10    15      10.4s <NULL>
2 mod_c2c         778ms 812.24ms     1.23      398MB     1.23    13    13      10.6s <NULL>
3 mod_c2c2        630ms 650.19ms     1.53      416MB     1.44    16    15      10.4s <NULL>
4 mod_c2c2vc      714ms 737.98ms     1.34      438MB     1.62    14    17      10.5s <NULL>
5 mod_c2c2br      751ms 797.43ms     1.26      441MB     1.84    13    19      10.4s <NULL>
6 mod_k           665ms  678.5ms     1.46      459MB     1.37    15    14      10.3s <NULL>
7 mod_k2          505ms 556.12ms     1.79      364MB     1.19    18    12        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 3

#+begin_quote
Setup 1
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.48s    1.55s     0.649     245MB     3.15     7    34      10.8s <NULL>
2 mod_c2c         1.15s    1.18s     0.832     292MB     3.05     9    33      10.8s <NULL>
3 mod_c2c2     895.01ms 976.02ms     1.01      275MB     3.12    11    34      10.9s <NULL>
4 mod_c2c2vc      1.09s    1.12s     0.889     289MB     3.26     9    33      10.1s <NULL>
5 mod_c2c2br      1.27s    1.29s     0.773     297MB     3.19     8    33      10.4s <NULL>
6 mod_k        932.44ms 959.37ms     1.02      283MB     2.88    11    31      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    6.16s    6.35s     0.157    6.07GB    1.57      2    20      12.7s <NULL>
2 mod_c2c         3.49s    3.56s     0.283    3.18GB    0.753     3     8      10.6s <NULL>
3 mod_c2c2        2.86s    2.96s     0.334    3.44GB    0.920     4    11        12s <NULL>
4 mod_c2c2vc         3s    3.15s     0.319    3.44GB    0.958     4    12      12.5s <NULL>
5 mod_c2c2br      3.11s    3.32s     0.306    3.46GB    1.07      4    14      13.1s <NULL>
6 mod_k           2.94s    2.99s     0.334     3.8GB    1.00      4    12        12s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    858ms    884ms      1.10     410MB     1.70    11    17        10s <NULL>
2 mod_c2c         739ms    761ms      1.28     398MB     1.28    13    13      10.1s <NULL>
3 mod_c2c2        593ms    605ms      1.65     416MB     1.56    17    16      10.3s <NULL>
4 mod_c2c2vc      680ms    694ms      1.43     438MB     1.72    15    18      10.5s <NULL>
5 mod_c2c2br      727ms    767ms      1.29     441MB     1.88    13    19      10.1s <NULL>
6 mod_k           619ms    640ms      1.55     459MB     1.45    16    15      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    1.49s    1.53s     0.650     245MB     3.34     7    36      10.8s <NULL>
2 mod_c2c         1.22s    1.26s     0.791     292MB     3.26     8    33      10.1s <NULL>
3 mod_c2c2      922.6ms 946.62ms     0.984     275MB     2.95    10    30      10.2s <NULL>
4 mod_c2c2vc      1.13s    1.18s     0.837     289MB     2.98     9    32      10.8s <NULL>
5 mod_c2c2br      1.42s    1.44s     0.692     297MB     2.97     7    30      10.1s <NULL>
6 mod_k              1s    1.04s     0.957     283MB     2.68    10    28      10.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    7.49s     7.9s     0.127    6.07GB    1.08      2    17      15.8s <NULL>
2 mod_c2c         3.67s    3.67s     0.271    3.18GB    0.722     3     8      11.1s <NULL>
3 mod_c2c2        2.71s    2.72s     0.368    3.44GB    0.827     4     9      10.9s <NULL>
4 mod_c2c2vc      2.87s    2.91s     0.345    3.44GB    0.947     4    11      11.6s <NULL>
5 mod_c2c2br      3.12s    3.22s     0.310    3.46GB    1.09      4    14      12.9s <NULL>
6 mod_k           2.81s    2.87s     0.347     3.8GB    0.781     4     9      11.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 6 × 13
  expression        min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    895ms    919ms      1.08     410MB     1.67    11    17      10.2s <NULL>
2 mod_c2c         706ms    794ms      1.23     398MB     1.42    13    15      10.6s <NULL>
3 mod_c2c2        597ms    626ms      1.59     416MB     1.49    16    15        10s <NULL>
4 mod_c2c2vc      674ms    719ms      1.39     438MB     1.69    14    17        10s <NULL>
5 mod_c2c2br      760ms    789ms      1.26     441MB     1.74    13    18      10.3s <NULL>
6 mod_k           633ms    664ms      1.50     459MB     1.40    15    14        10s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial 2

#+begin_quote
Setup 1
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.36s  1.54s     0.646     245MB     3.97     7    43      10.8s <NULL>
2 mod_a                2.01s  2.05s     0.488     662MB     2.83     5    29      10.3s <NULL>
3 mod_a_re             2.01s  2.04s     0.489     663MB     2.74     5    28      10.2s <NULL>
4 mod_c                1.39s  1.41s     0.700     279MB     2.71     8    31      11.4s <NULL>
5 mod_c2c              1.13s  1.21s     0.811     292MB     2.88     9    32      11.1s <NULL>
6 mod_c_delta_d_del    1.61s  1.64s     0.609     314MB     3.22     7    37      11.5s <NULL>
7 mod_h                 1.6s  1.63s     0.603     382MB     3.62     7    42      11.6s <NULL>
8 mod_h2               1.69s  1.71s     0.586     391MB     3.61     6    37      10.2s <NULL>
9 mod_i                 1.5s  1.52s     0.634     326MB     2.90     7    32        11s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.58s   6.9s     0.145    6.07GB    1.74      2    24      13.8s <NULL>
2 mod_a                9.04s  9.28s     0.108    12.2GB    0.862     2    16      18.6s <NULL>
3 mod_a_re              9.4s  9.44s     0.106    12.2GB    0.900     2    17      18.9s <NULL>
4 mod_c                6.14s  6.19s     0.162    2.33GB    0.485     2     6      12.4s <NULL>
5 mod_c2c              3.88s  4.42s     0.233    3.18GB    0.698     3     9      12.9s <NULL>
6 mod_c_delta_d_del    6.91s     7s     0.143    3.16GB    0.714     2    10        14s <NULL>
7 mod_h                4.79s  4.99s     0.201    4.59GB    0.872     3    13      14.9s <NULL>
8 mod_h2               4.46s  4.95s     0.209     4.6GB    1.04      3    15      14.4s <NULL>
9 mod_i                6.16s   6.2s     0.161    3.51GB    0.565     2     7      12.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 9 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    900.55ms 920.98ms     1.07      410MB     1.85    11    19      10.3s <NULL>
2 mod_a              1.48s     1.6s     0.621     962MB     1.33     7    15      11.3s <NULL>
3 mod_a_re           1.41s    1.47s     0.658     962MB     1.41     7    15      10.6s <NULL>
4 mod_c           932.85ms 954.82ms     1.02      336MB     1.48    11    16      10.8s <NULL>
5 mod_c2c         733.78ms 742.11ms     1.34      398MB     1.44    14    15      10.4s <NULL>
6 mod_c_delta_d_… 998.11ms    1.07s     0.929     416MB     1.49    10    16      10.8s <NULL>
7 mod_h           925.79ms 963.71ms     1.04      534MB     1.89    11    20      10.6s <NULL>
8 mod_h2           948.9ms    1.07s     0.952     537MB     1.81    10    19      10.5s <NULL>
9 mod_i              1.16s    1.24s     0.814     455MB     1.18     9    13      11.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.46s  1.56s     0.629     245MB     3.51     7    39      11.1s <NULL>
2 mod_a                2.12s  2.19s     0.449     662MB     2.52     5    28      11.1s <NULL>
3 mod_a_re             2.12s  2.18s     0.457     663MB     2.65     5    29      10.9s <NULL>
4 mod_c                1.45s  1.53s     0.651     280MB     2.51     7    27      10.8s <NULL>
5 mod_c2c              1.16s   1.2s     0.794     292MB     2.88     8    29      10.1s <NULL>
6 mod_c_delta_d_del    1.76s  1.79s     0.555     314MB     2.87     6    31      10.8s <NULL>
7 mod_h                 1.7s  1.71s     0.578     382MB     3.47     6    36      10.4s <NULL>
8 mod_h2               1.74s  1.78s     0.561     391MB     3.46     6    37      10.7s <NULL>
9 mod_i                1.52s  1.56s     0.616     326MB     2.82     7    32      11.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 9 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         7.87s  8.05s    0.124     6.07GB    1.30      2    21      16.1s <NULL>
2 mod_a               10.88s 10.88s    0.0919    12.2GB    0.643     1     7      10.9s <NULL>
3 mod_a_re            10.11s 10.11s    0.0989    12.2GB    0.594     1     6      10.1s <NULL>
4 mod_c                7.09s  7.27s    0.137     2.33GB    0.481     2     7      14.5s <NULL>
5 mod_c2c              3.74s  3.84s    0.257     3.18GB    0.685     3     8      11.7s <NULL>
6 mod_c_delta_d_del    7.43s  7.44s    0.134     3.16GB    0.672     2    10      14.9s <NULL>
7 mod_h                4.37s  4.39s    0.226     4.59GB    0.978     3    13      13.3s <NULL>
8 mod_h2               4.75s  4.77s    0.206      4.6GB    1.03      3    15      14.6s <NULL>
9 mod_i                7.01s  7.12s    0.141     3.51GB    0.492     2     7      14.2s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 9 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del       1.01s    1.04s     0.955     410MB     1.53    10    16      10.5s <NULL>
2 mod_a              1.73s    1.75s     0.570     962MB     1.24     6    13      10.5s <NULL>
3 mod_a_re           1.57s    1.67s     0.603     962MB     1.21     7    14      11.6s <NULL>
4 mod_c              1.13s    1.16s     0.838     336MB     1.12     9    12      10.7s <NULL>
5 mod_c2c         844.59ms 882.31ms     1.09      398MB     1.38    11    14      10.1s <NULL>
6 mod_c_delta_d_…    1.21s    1.32s     0.755     416MB     1.42     8    15      10.6s <NULL>
7 mod_h           985.65ms    1.02s     0.967     535MB     1.74    10    18      10.3s <NULL>
8 mod_h2             1.04s     1.1s     0.904     538MB     1.63    10    18      11.1s <NULL>
9 mod_i              1.28s    1.31s     0.757     455MB     1.04     8    11      10.6s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

* partial

#+begin_quote
orig/alt

 1 lgmem_no_del 502ms  519ms      1.89        NA     2.49    19    25      10.1s <NULL> <NULL>
 2 mod_a        707ms  737ms      1.36        NA     2.14    14    22      10.3s <NULL> <NULL>
 3 mod_a_re     638ms  659ms      1.47        NA     2.06    15    21      10.2s <NULL> <NULL>
 5 mod_c        463ms  482ms      2.07        NA     1.87    21    19      10.1s <NULL> <NULL>
12 mod_h        552ms  563ms      1.77        NA     2.46    18    25      10.2s <NULL> <NULL>
13 mod_h2       570ms  611ms      1.59        NA     2.39    16    24      10.1s <NULL> <NULL>
15 mod_i        520ms  537ms      1.85        NA     2.04    19    21      10.3s <NULL> <NULL>

alt/orig

 1 lgmem_no_d…  1.81s   1.9s    0.524         NA    2.27      6    26      11.4s <NULL> <NULL>
 2 mod_a           3s  3.19s    0.315         NA    2.68      4    34      12.7s <NULL> <NULL>
 3 mod_a_re     2.93s     3s    0.333         NA    1.08      4    13        12s <NULL> <NULL>
 5 mod_c        1.98s  1.99s    0.503         NA    0.503     6     6      11.9s <NULL> <NULL>
12 mod_h        1.38s  1.43s    0.686         NA    0.979     7    10      10.2s <NULL> <NULL>
13 mod_h2       1.38s  1.48s    0.673         NA    0.961     7    10      10.4s <NULL> <NULL>
15 mod_i        1.96s  1.98s    0.503         NA    0.503     6     6      11.9s <NULL> <NULL>

lger fewer

 1 lgmem_no_del   868.75ms  930.3ms     1.08         NA    1.37     11    14      10.2s <NULL>
 2 mod_a             1.48s    1.49s     0.657        NA    1.13      7    12      10.7s <NULL>
 3 mod_a_re          1.46s     1.5s     0.670        NA    1.24      7    13      10.4s <NULL>
 5 mod_c          971.21ms    1.02s     0.977        NA    0.879    10     9      10.2s <NULL>
12 mod_h          964.61ms 993.91ms     0.982        NA    1.47     10    15      10.2s <NULL>
13 mod_h2         982.86ms 995.44ms     1.00         NA    1.55     11    17        11s <NULL>
15 mod_i             1.19s    1.33s     0.732        NA    0.824     8     9      10.9s <NULL>

lger fewer DTthreads(1)

 1 lgmem_no_del   954.74ms 966.33ms     1.03         NA    1.32     11    14      10.6s <NULL>
 2 mod_a             1.57s    1.58s     0.628        NA    1.35      7    15      11.1s <NULL>
 3 mod_a_re          1.51s    1.54s     0.636        NA    1.18      7    13        11s <NULL>
 5 mod_c             1.06s    1.12s     0.895        NA    0.795     9     8      10.1s <NULL>
12 mod_h             1.03s    1.04s     0.951        NA    1.43     10    15      10.5s <NULL>
13 mod_h2            1.02s    1.06s     0.941        NA    1.41     10    15      10.6s <NULL>
15 mod_i             1.19s    1.23s     0.806        NA    0.895     9    10      11.2s <NULL>
#+end_quote

seems like h approaches probably best balanced?

* a bit more systematic

#+begin_src r
setups <- tribble(
  ~snaps, ~DTthreads,
  snapshots, 6,
  alt_snapshots, 6,
  larger_fewer_snapshots, 6,
  snapshots, 1,
  alt_snapshots, 1,
  larger_fewer_snapshots, 1,
  )
#+end_src

#+begin_quote
Setup 1
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.47s  1.49s     0.652     245MB     3.17     7    34      10.7s <NULL>
2 mod_a                2.09s   2.1s     0.477     663MB     2.10     5    22      10.5s <NULL>
3 mod_a_re             2.05s   2.1s     0.476     662MB     2.00     5    21      10.5s <NULL>
4 mod_c                1.42s  1.44s     0.690     279MB     1.97     7    20      10.1s <NULL>
5 mod_c_delta_d_del    1.66s  1.73s     0.569     314MB     2.18     6    23      10.5s <NULL>
6 mod_h                 1.6s  1.62s     0.611     382MB     2.70     7    31      11.5s <NULL>
7 mod_h2               1.66s  1.68s     0.594     391MB     2.67     6    27      10.1s <NULL>
8 mod_i                1.59s  1.62s     0.615     326MB     2.20     7    25      11.4s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 2
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.12s  6.27s     0.160    6.07GB    1.36      2    17      12.5s <NULL>
2 mod_a                8.75s  9.16s     0.109    12.2GB    0.710     2    13      18.3s <NULL>
3 mod_a_re             9.35s  9.54s     0.105    12.2GB    0.733     2    14      19.1s <NULL>
4 mod_c                6.36s  6.38s     0.157    2.33GB    0.392     2     5      12.8s <NULL>
5 mod_c_delta_d_del    6.38s  6.41s     0.156    3.16GB    0.546     2     7      12.8s <NULL>
6 mod_h                4.19s  4.29s     0.235    4.59GB    0.782     3    10      12.8s <NULL>
7 mod_h2               4.31s  4.37s     0.229     4.6GB    0.839     3    11      13.1s <NULL>
8 mod_i                6.01s  6.05s     0.165    3.51GB    0.496     2     6      12.1s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 3
# A tibble: 8 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    815.32ms 829.21ms     1.20      411MB    1.50     12    15        10s <NULL>
2 mod_a              1.43s    1.44s     0.694     962MB    0.991     7    10      10.1s <NULL>
3 mod_a_re            1.4s    1.45s     0.690     962MB    0.986     7    10      10.1s <NULL>
4 mod_c           941.92ms 954.45ms     1.05      336MB    1.05     11    11      10.5s <NULL>
5 mod_c_delta_d_…    1.04s    1.06s     0.925     416MB    1.20     10    13      10.8s <NULL>
6 mod_h           956.62ms 978.26ms     1.01      534MB    1.56     11    17      10.9s <NULL>
7 mod_h2          974.15ms 992.94ms     1.00      538MB    1.55     11    17        11s <NULL>
8 mod_i              1.11s    1.16s     0.860     455MB    0.956     9    10      10.5s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 4
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         1.51s  1.52s     0.655     245MB     2.53     7    27      10.7s <NULL>
2 mod_a                2.17s  2.17s     0.459     663MB     2.29     5    25      10.9s <NULL>
3 mod_a_re             2.17s  2.18s     0.457     662MB     2.19     5    24      10.9s <NULL>
4 mod_c                 1.4s   1.5s     0.647     280MB     2.03     7    22      10.8s <NULL>
5 mod_c_delta_d_del    1.69s  1.69s     0.586     314MB     2.34     6    24      10.2s <NULL>
6 mod_h                1.63s  1.66s     0.598     382MB     2.69     6    27        10s <NULL>
7 mod_h2               1.69s  1.72s     0.579     391MB     2.61     6    27      10.4s <NULL>
8 mod_i                1.64s  1.68s     0.597     326MB     2.22     7    26      11.7s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 5
# A tibble: 8 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>        <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del         6.94s  7.24s     0.138    6.07GB    1.31      2    19      14.5s <NULL>
2 mod_a                 9.7s  9.84s     0.102    12.2GB    1.07      2    21      19.7s <NULL>
3 mod_a_re              9.6s   9.6s     0.104    12.2GB    0.677     2    13      19.2s <NULL>
4 mod_c                 6.6s  6.65s     0.150    2.33GB    0.376     2     5      13.3s <NULL>
5 mod_c_delta_d_del    6.93s  6.96s     0.144    3.16GB    0.503     2     7      13.9s <NULL>
6 mod_h                4.31s  4.32s     0.232    4.59GB    0.849     3    11      12.9s <NULL>
7 mod_h2               4.34s   4.4s     0.227     4.6GB    0.758     3    10      13.2s <NULL>
8 mod_i                 6.6s  6.64s     0.151    3.51GB    0.452     2     6      13.3s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Setup 6
# A tibble: 8 × 13
  expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
  <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
1 lgmem_no_del    938.69ms 951.99ms     1.05      410MB    1.24     11    13      10.5s <NULL>
2 mod_a              1.53s    1.55s     0.640     962MB    1.01      7    11      10.9s <NULL>
3 mod_a_re           1.51s    1.52s     0.655     962MB    0.936     7    10      10.7s <NULL>
4 mod_c              1.05s    1.07s     0.924     336MB    0.924    10    10      10.8s <NULL>
5 mod_c_delta_d_…    1.13s    1.15s     0.872     416MB    1.16      9    12      10.3s <NULL>
6 mod_h              1.02s    1.06s     0.940     534MB    1.41     10    15      10.6s <NULL>
7 mod_h2             1.03s    1.06s     0.940     538MB    1.41     10    15      10.6s <NULL>
8 mod_i              1.17s     1.2s     0.834     455MB    1.02      9    11      10.8s <NULL>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning messages:
1: Some expressions had a GC in every iteration; so filtering is disabled. 
2: Some expressions had a GC in every iteration; so filtering is disabled. 
3: Some expressions had a GC in every iteration; so filtering is disabled. 
4: Some expressions had a GC in every iteration; so filtering is disabled. 
5: Some expressions had a GC in every iteration; so filtering is disabled. 
6: Some expressions had a GC in every iteration; so filtering is disabled. 
#+end_quote

